server/app/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from rest_framework import routers
from rest_framework.authtoken import views as authviews

from . import views

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter(trailing_slash=False)
router.register(r'users', views.UserViewSet)
router.register(r'regions', views.RegionViewSet)
router.register(r'schools', views.SchoolViewSet)
router.register(r'grades', views.GradeViewSet)
router.register(r'subjects', views.SubjectViewSet)
router.register(r'tags', views.TagViewSet)
router.register(r'levels', views.LevelViewSet)
router.register(r'profiles', views.ProfileViewSet)
router.register(r'teachers', views.TeacherViewSet)
router.register(r'memberservices', views.MemberserviceViewSet)
router.register(r'coupons', views.CouponViewSet)
router.register(r'weeklytimeslots', views.WeeklyTimeSlotViewSet)
router.register(r'parents', views.ParentViewSet)
router.register(r'timeslots', views.TimeSlotViewSet)
router.register(r'orders', views.OrderViewSet)
router.register(r'comments', views.CommentViewSet)
router.register(r'favorites', views.FavoriteViewSet)
router.register(r'liveclasses', views.LiveClassViewSet)
router.register(r'exercise', views.ExerciseSubmitViewSet)


urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='app/index.html')),
    url(r'^api-auth', include(
        'rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/teachers/(?P<teacher_id>\d+)/weeklytimeslots',
        views.TeacherWeeklyTimeSlot.as_view(),
        name='teacher_weekly_time_slot'),
    url(r'^api/v1/token-auth', authviews.obtain_auth_token),
    url(r'^api/v1/policy', views.Policy.as_view(), name='policy'),
    url(r'^api/v1/subject/(?P<subject_id>\d+)/record',
        views.SubjectRecord.as_view(), name='subject_record'),
    url(r'^api/v1/sms', views.Sms.as_view(), name='sms'),
    url(r'^api/v1/charge_succeeded', views.ChargeSucceeded.as_view(),
        name='charge_succeeded'),
    url(r'^api/v1/concrete/timeslots', views.ConcreteTimeSlots.as_view(),
        name='concrete_time_slot'),
    url(r'^api/v1/unpaid_count', views.UnpaidCount.as_view(),
        name='unpaid_count'),
    url(r'^api/v1/my_center', views.ParentCenter.as_view(),
        name='my_center'),
    url(r'^api/v1/study_report(\/?)$', views.StudyReportView.as_view(),
        name='study_report_api'),
    url(r'^api/v1/study_report/(?P<subject>\w+)(\/?)$', views.StudyReportView.as_view(),
        name="study_report_subject"),
    # url(r'^api/v1/study_report/(?P<subject>\w+)/(?P<category>\w+)(\/?)$', views.StudyReportView.as_view(),
    #     name="study_report_category"),
    url(r'^api/v1/teacher/(?P<teacher_id>\d+)/school/(?P<school_id>\d+)/prices',
        views.TeacherSchoolPrices.as_view(), name='teacher_school_prices'),
    url(r'^api/v1/pad/login', views.PadLogin.as_view(), name='pad_login'),
    url(r'^api/v1/pad/status', views.PadStatus.as_view(), name='pad_status'),
    url(r'^api/v1/pad/question', views.PadQuestion.as_view(), name='pad_question'),
    url(r'^api/v1/pad/submit', views.PadSubmit.as_view(), name='pad_submit'),
    url(r'^api/v1/', include(router.urls)),
]

server/lecturer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^index$', views.IndexView.as_view(), name="index"),
    url(r'^login$', views.LoginView.as_view(), name="login"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^timeslots$', views.TimeslotsView.as_view(), name="timeslots"),
    url(r'^living$', views.LivingView.as_view(), name="living"),
    url(r'^timeslot/(?P<tsid>\d+)/questions$',
        views.LCTimeslotQuestionsView.as_view(), name="timeslot-questions"),
    url(r'^exercise/store$',
        views.ExerciseStore.as_view(), name="exercise-store"),
    url(r'^api/exercise/store$',
        views.ApiExerciseStore.as_view(), name="api-exercise-store"),
]

server/server/urls.py
import django
import os
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.conf import settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('app.urls')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^teacher/', include('teacher.urls', namespace='teacher')),
    url(r'^staff/', include('staff.urls', namespace='staff')),
    url(r'^import_/', include('import_.urls', namespace='import_')),
    url(r'^wechat/', include('wechat.urls', namespace='wechat')),
    url(r'^lecturer/', include('lecturer.urls', namespace='lecturer')),
    url(r'^upload/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^api/v1/(?P<path>.*(\.json|\.yaml))$', django.views.static.serve,
        {'document_root': os.path.join(BASE_DIR, "app", "api")}),
    url(r'^', include('web.urls', namespace='web')),
    url(r'^favicon\.ico$', django.views.generic.base.RedirectView.as_view(
        url=static('common/icons/favicon.ico'), permanent=True)),
]

server/staff/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.login, name="login"),
    url(r'^login/auth/$', views.login_auth, name="login_auth"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^analysis$', views.AnalysisView.as_view(), name="analysis"),
    url(r'^students/$', views.StudentView.as_view(), name="students"),
    url(r'^students/schedule/manage/$', views.StudentScheduleManageView.as_view(), name="student_schedule_manage"),
    url(r'^students/schedule/changelog/$', views.StudentScheduleChangelogView.as_view(), name="student_schedule_changelog"),
    url(r'^students/schedule/action/$', views.StudentScheduleActionView.as_view(), name="student_schedule_action"),
    url(r'^teachers/$', views.TeacherView.as_view(), name="teachers"),
    url(r'^teachers/unpublished/$', views.TeacherUnpublishedView.as_view(), name="teachers_unpublished"),
    url(r'^teachers/published/$', views.TeacherPublishedView.as_view(), name="teachers_published"),
    url(r'^teachers/unpublished/(?P<tid>\d+)/edit$', views.TeacherUnpublishedEditView.as_view(), name="teachers_unpublished_edit"),
    url(r'^teachers/published/(?P<tid>\d+)/edit$', views.TeacherUnpublishedEditView.as_view(), name="teachers_published_edit"),
    url(r'^teachers/action/$', views.TeacherActionView.as_view(), name="teachers_action"),
    url(r'^teachers/bankcard/list/$', views.TeacherBankcardView.as_view(), name="teachers_bankcard_list"),
    url(r'^teachers/income/list/$', views.TeacherIncomeView.as_view(), name="teachers_income_list"),
    url(r'^teachers/income/(?P<tid>\d+)/detail/$', views.TeacherIncomeDetailView.as_view(), name="teachers_income_detail"),
    url(r'^teachers/withdrawal/list/$', views.TeacherWithdrawalView.as_view(), name="teachers_withdrawal_list"),
    url(r'^schools/$', views.SchoolsView.as_view(), name="schools"),
    url(r'^school/$', views.SchoolView.as_view(), name='staff_school'),
    url(r'^school/timeslot$', views.SchoolTimeslotView.as_view(), name='school_timeslot'),
    url(r'^orders/review/$', views.OrderReviewView.as_view(), name="orders_review"),
    url(r'^orders/refund/$', views.OrderRefundView.as_view(), name="orders_refund"),
    url(r'^orders/action/$', views.OrderRefundActionView.as_view(), name="orders_action"),
    url(r'^coupons/list/$', views.CouponsListView.as_view(), name="coupons_list"),
    url(r'^coupon/config/$', views.CouponConfigView.as_view(), name="coupon_config"),
    url(r'^evaluations/$', views.EvaluationView.as_view(), name="evaluations"),
    url(r'^evaluations/action/$', views.EvaluationActionView.as_view(), name="evaluations_action"),
    url(r'^level/price/config/$', views.LevelPriceConfigView.as_view(), name="level_price_cfg"),
    url(r'^level/salary/config/$', views.LevelSalaryConfigView.as_view(), name="level_salary_cfg"),
    url(r'^school/account/info/$', views.SchoolAccountInfoView.as_view(), name="school_account_info"),
    url(r'^school/account/info_v2/$', views.SchoolAccountInfoViewV2.as_view(), name="school_account_info_v2"),
    url(r'^school/price/config/$', views.SchoolPriceConfigView.as_view(), name="school_price_cfg"),
    url(r'^school/account/income/records/$', views.SchoolIncomeRecordView.as_view(), name="school_income_records"),
    url(r'^school/account/income/audit/$', views.SchoolIncomeAuditView.as_view(), name="school_income_audit"),
    url(r'^school/account/income/records_v2/$', views.SchoolIncomeRecordViewV2.as_view(), name="school_income_records_v2"),
    url(r'^school/account/income/audit_v2/$', views.SchoolIncomeAuditViewV2.as_view(), name="school_income_audit_v2"),
    url(r'^region/(?P<rid>\d+)/$', views.RegionView.as_view(), name="region_config"),
    url(r'^course/live-course/$', views.LiveCourseView.as_view(), name="live_course"),
    url(r'^course/live-course/classroom/$', views.CreateClassRoomView.as_view(), name="create_room"),
    url(r'^course/live-course/list/$', views.LiveCourseListView.as_view(), name="live_course_list"),
    url(r'^course/live-course/detail/(?P<cid>\d+)/$$', views.LiveCourseView.as_view(), name="live_course_detail"),
    url(r'^auth/$', views.StaffAuthView.as_view(), name="staff_auth"),
]

server/teacher/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url(r'^login$', views.TeacherLogin.as_view(), name="login"),
    url(r'^logout/$', auth_views.logout_then_login, {"login_url": "/web/teacher"}, name="logout"),
    url(r'^doc/agree/$', TemplateView.as_view(template_name="teacher/doc/policy.html"), name="doc-agree"),
    url(r'^information/complete$', views.InformationComplete.as_view(), name="complete-information"),
    url(r'^register/progress$', views.RegisterProgress.as_view(), name="register-progress"),
    url(r'^first_page/$', views.FirstPage.as_view(), name="first-page"),
    url(r'^$', views.FirstPage.as_view(), name="default-page"),
    url(r'^my_school_timetable/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.MySchoolTimetable.as_view(), name="my-school-timetable"),
    url(r'^my_students/(?P<student_type>[0-9]{1})/(?P<page_offset>[0-9]+)/$', views.MyStudents.as_view(), name="my-students"),
    url(r'^my_evaluation/(?P<comment_type>[0-9]+)/(?P<page_offset>[0-9]+)/$', views.MyEvaluation.as_view(), name="my-evaluation"),
    url(r'^my_evaluation/(?P<comment_type>[0-9]+)/(?P<page_offset>[0-9]+)/reply/comment/(?P<id>\d+)$', views.CommentReply.as_view(), name="reply-comment"),
    url(r'^my_wallet/withdrawal/$', views.MyWalletWithdrawal.as_view(), name="my-wallet-withdrawal"),
    url(r'^my_wallet/withdrawal/result/$', views.MyWalletWithdrawalResult.as_view(), name="my-wallet-withdrawal-result"),
    url(r'^my_wallet/withdrawal/record/$', views.MyWalletWithdrawalRecord.as_view(), name="my-wallet-withdrawal-record"),
    url(r'^my_level/$', views.MyLevel.as_view(), name="my-level"),
    url(r'^generate_sms/$', views.GenerateSMS.as_view(), name="generate-sms"),
    url(r'^withdrawal_request/$', views.WithdrawalRequest.as_view(), name="withdrawal_request"),
    url(r'^certificate/$', views.CertificateView.as_view(), name="certificate"),
    url(r'^certificate/id/$', views.CertificateIDView.as_view(), name="certificate-id"),
    url(r'^certificate/academic/$', views.CertificateAcademicView.as_view(), name="certificate-academic"),
    url(r'^certificate/teaching/$', views.CertificateTeachingView.as_view(), name="certificate-teaching"),
    url(r'^certificate/english/$', views.CertificateEnglishView.as_view(), name="certificate-english"),
    url(r'^certificate/others/$', views.CertificateOthersView.as_view(), name="certificate-others"),
    url(r'^highscore/$', views.HighscoreView.as_view(), name="highscore"),
    url(r'^basic_doc/$', views.BasicDocument.as_view(), name="basic_doc"),
    url(r'^achievement$', views.AchievementView.as_view(), name="achievement"),
    url(r'^achievement/(?P<action>\w+)$', views.AchievementView.as_view(), name="achievement-add"),
    url(r'^achievement/(?P<action>\w+)/(?P<id>\d+)$', views.AchievementView.as_view(), name="achievement-edit"),
    url(r'^wallet/$', views.WalletView.as_view(), name="wallet"),
    url(r'^wallet/(?P<action>histories)/$', views.WalletView.as_view(), name="wallet-histories"),
    url(r'^wallet/bankcard/add/$', views.WalletBankcardView.as_view(), name="wallet-bankcard-add"),
    url(r'^wallet/bankcard/add/(?P<step>success)/$', views.WalletBankcardView.as_view(), name="wallet-bankcard-add-success"),
    url(r'^my_students/letter/(?P<student_type>[0-9]{1})/(?P<page_offset>[0-9]+)/(?P<student_id>[0-9]+)/$', views.StudentLetter.as_view(), name="student-letter"),
    url(r'^my_students/letter/(?P<student_type>[0-9]{1})/(?P<page_offset>[0-9]+)/(?P<student_id>[0-9]+)/(?P<letter_id>[0-9]+)$', views.StudentLetterView.as_view(), name="student-letter-view"),
    url(r'^kuailexue/account/$', views.KLXAccountView.as_view(), name="klx-account"),
    url(r'^schedule/weekly_config/$', views.ScheduleWeeklyConfigView.as_view(), name="schedule-weekly-config"),
]

server/web/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', views.PatriarchIndex.as_view(), name="patriarch-index"),
    url(r'^web/teacher', views.TeacherIndex.as_view(), name='teacher-index'),
    url(r'^policy', views.PolicyView.as_view(), name='policy'),
    url(r'^m/ad', views.AppADView.as_view(), name='app-ad'),
]

server/templates/base.html
{% load i18n admin_static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
<script type="text/javascript">window.__admin_utc_offset__ = "{% filter escapejs %}{% now "Z" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

{% include 'ga.html' %}
</body>
</html>

server/templates/footer.html
<div id="footer" class="footer">
  <div class="container">
    <small>
      &copy; Beijing Mala Online Network Technology Ltd &nbsp; |  &nbsp;

      <a href="{% url 'staff:index' %}" target="_blank">后台管理端</a> &nbsp; | &nbsp;
      <a href="{% url 'teacher:default-page' %}" target="_blank">老师端</a> &nbsp; | &nbsp;
      <a href="{% url 'web:patriarch-index' %}" target="_blank">官网</a> &nbsp; | &nbsp;
      <a href="{% url 'lecturer:home' %}" target="_blank">双师后台</a> &nbsp; | &nbsp;
      <a href="{% url 'wechat:teachers' %}" target="_blank">微信端</a> &nbsp; | &nbsp;
      <a href="http://j.malalaoshi.com" target="_blank">Jira</a> &nbsp; | &nbsp;
      <a href="https://github.com/malaonline/malalaoshi" target="_blank">Github</a> &nbsp; | &nbsp;
      <a href="http://ci.malalaoshi.com" target="_blank">CI</a> &nbsp; | &nbsp;
      <a href="http://wiki.malalaoshi.com" target="_blank">Wiki</a> &nbsp; | &nbsp;
      Revision: {{rev}} &nbsp; | &nbsp;
      Deployed at: {{deployed_at}}
    </small>
  </div>
</div>

server/templates/ga.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65644538-3', 'auto');
  ga('send', 'pageview');

  {% if user.is_authenticated %}
  ga('set', 'userId', '{{user.id}}');
  {% endif %}

</script>

server/templates/m_loading_dialog.html
<div class="m_loading_dialog" id="mLoadingDialog" style="display: none">
    <div class="m_loading_mask"></div>
    <div class="m_loading_body">
        <div class="m_loading_ani">
            <div class="m_loading_leaf m_loading_leaf_0"></div>
            <div class="m_loading_leaf m_loading_leaf_1"></div>
            <div class="m_loading_leaf m_loading_leaf_2"></div>
            <div class="m_loading_leaf m_loading_leaf_3"></div>
            <div class="m_loading_leaf m_loading_leaf_4"></div>
            <div class="m_loading_leaf m_loading_leaf_5"></div>
            <div class="m_loading_leaf m_loading_leaf_6"></div>
            <div class="m_loading_leaf m_loading_leaf_7"></div>
            <div class="m_loading_leaf m_loading_leaf_8"></div>
            <div class="m_loading_leaf m_loading_leaf_9"></div>
            <div class="m_loading_leaf m_loading_leaf_10"></div>
            <div class="m_loading_leaf m_loading_leaf_11"></div>
        </div>
        <p class="m_loading_text" id="mLoadingText"></p>
    </div>
</div>

server/templates/pagination_nav.html
{% load custom_tags %}
<nav>
    <ul class="pagination">
        <li class="{% if not pager.page or pager.page <= 1 %}disabled{% endif %}">
            <a href="javascript:void(0)" aria-label="First" data-pageto="1"><span aria-hidden="true">&laquo;</span></a>
        </li>
        <li class="{% if not pager.page or pager.page <= 1 %}disabled{% endif %}">
            <a href="javascript:void(0)" aria-label="Previous" data-pageto="{{ pager.page|add:-1 }}"><span aria-hidden="true">&lt;</span></a>
        </li>
        {% if pager.show_start > 1 %}
            <li class="">
                <span aria-hidden="true">...</span>
            </li>
        {% endif %}
        {% for i in pager.show_page_range %}
            <li class="{% if pager.page == i %}active{% endif %}">
                <a href="javascript:void(0)" data-pageto="{{ i }}">{{ i }}</a>
            </li>
        {% endfor %}
        {% if pager.total_page and pager.show_end < pager.total_page %}
            <li class="">
                <span aria-hidden="true">...</span>
            </li>
        {% endif %}
        <li class="{% if not pager.page or pager.page >= pager.total_page %}disabled{% endif %}">
            <a href="javascript:void(0)" aria-label="Next" data-pageto="{{ pager.page|add:1 }}"> <span aria-hidden="true">&gt;</span></a>
        </li>
        <li class="{% if not pager.page or pager.page >= pager.total_page %}disabled{% endif %}">
            <a href="javascript:void(0)" aria-label="Last" data-pageto="{{ pager.total_page }}"> <span aria-hidden="true">&raquo;</span></a>
        </li>
    </ul>
</nav>