server/app/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from rest_framework import routers
from rest_framework.authtoken import views as authviews

from . import views

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter(trailing_slash=False)
router.register(r'users', views.UserViewSet)
router.register(r'regions', views.RegionViewSet)
router.register(r'schools', views.SchoolViewSet)
router.register(r'grades', views.GradeViewSet)
router.register(r'subjects', views.SubjectViewSet)
router.register(r'tags', views.TagViewSet)
router.register(r'levels', views.LevelViewSet)
router.register(r'profiles', views.ProfileViewSet)
router.register(r'teachers', views.TeacherViewSet)
router.register(r'memberservices', views.MemberserviceViewSet)
router.register(r'coupons', views.CouponViewSet)
router.register(r'weeklytimeslots', views.WeeklyTimeSlotViewSet)
router.register(r'parents', views.ParentViewSet)
router.register(r'timeslots', views.TimeSlotViewSet)
router.register(r'orders', views.OrderViewSet)
router.register(r'comments', views.CommentViewSet)
router.register(r'favorites', views.FavoriteViewSet)
router.register(r'liveclasses', views.LiveClassViewSet)
router.register(r'exercise', views.ExerciseSubmitViewSet)


urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='app/index.html')),
    url(r'^api-auth', include(
        'rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/teachers/(?P<teacher_id>\d+)/weeklytimeslots',
        views.TeacherWeeklyTimeSlot.as_view(),
        name='teacher_weekly_time_slot'),
    url(r'^api/v1/token-auth', authviews.obtain_auth_token),
    url(r'^api/v1/policy', views.Policy.as_view(), name='policy'),
    url(r'^api/v1/subject/(?P<subject_id>\d+)/record',
        views.SubjectRecord.as_view(), name='subject_record'),
    url(r'^api/v1/sms', views.Sms.as_view(), name='sms'),
    url(r'^api/v1/charge_succeeded', views.ChargeSucceeded.as_view(),
        name='charge_succeeded'),
    url(r'^api/v1/concrete/timeslots', views.ConcreteTimeSlots.as_view(),
        name='concrete_time_slot'),
    url(r'^api/v1/unpaid_count', views.UnpaidCount.as_view(),
        name='unpaid_count'),
    url(r'^api/v1/my_center', views.ParentCenter.as_view(),
        name='my_center'),
    url(r'^api/v1/study_report(\/?)$', views.StudyReportView.as_view(),
        name='study_report_api'),
    url(r'^api/v1/study_report/(?P<subject>\w+)(\/?)$', views.StudyReportView.as_view(),
        name="study_report_subject"),
    # url(r'^api/v1/study_report/(?P<subject>\w+)/(?P<category>\w+)(\/?)$', views.StudyReportView.as_view(),
    #     name="study_report_category"),
    url(r'^api/v1/teacher/(?P<teacher_id>\d+)/school/(?P<school_id>\d+)/prices',
        views.TeacherSchoolPrices.as_view(), name='teacher_school_prices'),
    url(r'^api/v1/pad/login', views.PadLogin.as_view(), name='pad_login'),
    url(r'^api/v1/pad/status', views.PadStatus.as_view(), name='pad_status'),
    url(r'^api/v1/pad/question', views.PadQuestion.as_view(), name='pad_question'),
    url(r'^api/v1/pad/submit', views.PadSubmit.as_view(), name='pad_submit'),
    url(r'^api/v1/', include(router.urls)),
]

server/server/urls.py
import django
import os
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.conf import settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('app.urls')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^teacher/', include('teacher.urls', namespace='teacher')),
    url(r'^staff/', include('staff.urls', namespace='staff')),
    url(r'^import_/', include('import_.urls', namespace='import_')),
    url(r'^wechat/', include('wechat.urls', namespace='wechat')),
    url(r'^lecturer/', include('lecturer.urls', namespace='lecturer')),
    url(r'^upload/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^api/v1/(?P<path>.*(\.json|\.yaml))$', django.views.static.serve,
        {'document_root': os.path.join(BASE_DIR, "app", "api")}),
    url(r'^', include('web.urls', namespace='web')),
    url(r'^favicon\.ico$', django.views.generic.base.RedirectView.as_view(
        url=static('common/icons/favicon.ico'), permanent=True)),
]

server/teacher/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url(r'^login$', views.TeacherLogin.as_view(), name="login"),
    url(r'^logout/$', auth_views.logout_then_login, {"login_url": "/web/teacher"}, name="logout"),
    url(r'^doc/agree/$', TemplateView.as_view(template_name="teacher/doc/policy.html"), name="doc-agree"),
    url(r'^information/complete$', views.InformationComplete.as_view(), name="complete-information"),
    url(r'^register/progress$', views.RegisterProgress.as_view(), name="register-progress"),
    url(r'^first_page/$', views.FirstPage.as_view(), name="first-page"),
    url(r'^$', views.FirstPage.as_view(), name="default-page"),
    url(r'^my_school_timetable/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.MySchoolTimetable.as_view(), name="my-school-timetable"),
    url(r'^my_students/(?P<student_type>[0-9]{1})/(?P<page_offset>[0-9]+)/$', views.MyStudents.as_view(), name="my-students"),
    url(r'^my_evaluation/(?P<comment_type>[0-9]+)/(?P<page_offset>[0-9]+)/$', views.MyEvaluation.as_view(), name="my-evaluation"),
    url(r'^my_evaluation/(?P<comment_type>[0-9]+)/(?P<page_offset>[0-9]+)/reply/comment/(?P<id>\d+)$', views.CommentReply.as_view(), name="reply-comment"),
    url(r'^my_wallet/withdrawal/$', views.MyWalletWithdrawal.as_view(), name="my-wallet-withdrawal"),
    url(r'^my_wallet/withdrawal/result/$', views.MyWalletWithdrawalResult.as_view(), name="my-wallet-withdrawal-result"),
    url(r'^my_wallet/withdrawal/record/$', views.MyWalletWithdrawalRecord.as_view(), name="my-wallet-withdrawal-record"),
    url(r'^my_level/$', views.MyLevel.as_view(), name="my-level"),
    url(r'^generate_sms/$', views.GenerateSMS.as_view(), name="generate-sms"),
    url(r'^withdrawal_request/$', views.WithdrawalRequest.as_view(), name="withdrawal_request"),
    url(r'^certificate/$', views.CertificateView.as_view(), name="certificate"),
    url(r'^certificate/id/$', views.CertificateIDView.as_view(), name="certificate-id"),
    url(r'^certificate/academic/$', views.CertificateAcademicView.as_view(), name="certificate-academic"),
    url(r'^certificate/teaching/$', views.CertificateTeachingView.as_view(), name="certificate-teaching"),
    url(r'^certificate/english/$', views.CertificateEnglishView.as_view(), name="certificate-english"),
    url(r'^certificate/others/$', views.CertificateOthersView.as_view(), name="certificate-others"),
    url(r'^highscore/$', views.HighscoreView.as_view(), name="highscore"),
    url(r'^basic_doc/$', views.BasicDocument.as_view(), name="basic_doc"),
    url(r'^achievement$', views.AchievementView.as_view(), name="achievement"),
    url(r'^achievement/(?P<action>\w+)$', views.AchievementView.as_view(), name="achievement-add"),
    url(r'^achievement/(?P<action>\w+)/(?P<id>\d+)$', views.AchievementView.as_view(), name="achievement-edit"),
    url(r'^wallet/$', views.WalletView.as_view(), name="wallet"),
    url(r'^wallet/(?P<action>histories)/$', views.WalletView.as_view(), name="wallet-histories"),
    url(r'^wallet/bankcard/add/$', views.WalletBankcardView.as_view(), name="wallet-bankcard-add"),
    url(r'^wallet/bankcard/add/(?P<step>success)/$', views.WalletBankcardView.as_view(), name="wallet-bankcard-add-success"),
    url(r'^my_students/letter/(?P<student_type>[0-9]{1})/(?P<page_offset>[0-9]+)/(?P<student_id>[0-9]+)/$', views.StudentLetter.as_view(), name="student-letter"),
    url(r'^my_students/letter/(?P<student_type>[0-9]{1})/(?P<page_offset>[0-9]+)/(?P<student_id>[0-9]+)/(?P<letter_id>[0-9]+)$', views.StudentLetterView.as_view(), name="student-letter-view"),
    url(r'^kuailexue/account/$', views.KLXAccountView.as_view(), name="klx-account"),
    url(r'^schedule/weekly_config/$', views.ScheduleWeeklyConfigView.as_view(), name="schedule-weekly-config"),
]

server/teacher/forms.py
from django import forms


class CommentReplyForm(forms.Form):
    reply = forms.CharField(max_length=100, min_length=6,
                            widget=forms.Textarea(attrs={"class": "reply-content"}),
                            label=None
                            )

server/templates/teacher/achievement/achievement.html
{% extends "teacher/teacher_frame.html" %}

{% load staticfiles %}
{% load compile_static %}
{% block title %}
    特殊成果
{% endblock %}
{% block addition_header %}
    <link rel="stylesheet" href="{% static 'teacher/less/achievement/achievement.less'|compile %}?{% lorem 1 w random%}">
{% endblock %}
{% block addition_js %}
    <script src="{% static 'teacher/js/achievement/achievement.js' %}?{% lorem 1 w random%}"></script>
    <script>var maxCount = '{{ MAX_COUNT }}';</script>
{% endblock %}

{% block breadcrumbs %}
    <span class="title">个人设置</span>
    &gt;
    <span>特殊成果</span>
{% endblock %}

{% block maincontent %}
    {% csrf_token %}
    <div class="list-group" id="achievementsList">
        {% for achievement in achievements %}
            <div class="list-group-item" achieveId="{{ achievement.id }}">
                <div class="pull-right">
                    <a class="btn btn-default btn-small" href="{% url 'teacher:achievement-edit' action='edit' id=achievement.id %}" data-action="edit-achievement">编辑</a>
                    <button class="btn btn-default btn-small" data-action="delete-achievement">删除</button>
                </div>
                <div class="title">
                    {{ achievement.title }}
                </div>
                <div class="img-box">
                    <img src="{{ achievement.img_url }}">
                </div>
            </div>
        {% endfor %}
    </div>
    <div>
        <a class="btn btn-success" data-url="{% url 'teacher:achievement-add' action='add' %}" id="btnAddAchievement">添加</a>
    </div>
{% endblock %}

server/templates/teacher/achievement/achievement_edit.html
{% extends "teacher/teacher_frame.html" %}

{% load staticfiles %}
{% load compile_static %}
{% block title %}
    特殊成果
{% endblock %}
{% block addition_header %}
    <link rel="stylesheet" href="{% static 'teacher/less/achievement/achievement.less'|compile %}?{% lorem 1 w random%}">
{% endblock %}
{% block addition_js %}
    <script src="{% static 'teacher/js/achievement/achievement.js' %}?{% lorem 1 w random%}"></script>
    <script>var listPageUrl = '{% url 'teacher:achievement' %}';</script>
{% endblock %}

{% block breadcrumbs %}
    {% csrf_token %}
    <span class="title">个人设置</span>
    &gt;
    <a href="{% url 'teacher:achievement' %}"><span>特殊成果</span></a>
    &gt;
    <span>{{ achieve_title }}</span>
{% endblock %}

{% block maincontent %}
    <form class="form-horizontal" id="achieveEditForm" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" id="id" name="id" value="{{ achieve.id }}">
        <div class="form-group">
            <label for="name" class="col-sm-2 control-label">成果名称</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="title" name="title" value="{{ achieve.title }}" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-2">{# empty #}</div>
            <div class="col-sm-3">
                <div class="img-upload-box">
                    <div class="img-box">
                        <img src="{{ achieve.img_url }}">
                    </div>
                    <div class="img-preview-box"><img src=""></div>
                    <div class="uploading-hint-box"></div>
                    <span class="file-input-mask text-center">
                        <span>上传图片</span>
                        <input title="请选择图片" type="file" name="achieveImg" multiple=""/>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group {% if error_msg %}has-error{% endif %}">
            <div class="col-sm-2">{# empty #}</div>
            <div class="col-sm-10">
                <span class="help-block">{{ error_msg }}</span>
                <button type="button" class="btn btn-success" data-action="save">保存</button>
                <button type="button" class="btn btn-default" data-action="cancel">取消</button>
            </div>
        </div>
    </form>
{% endblock %}