server/app/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from rest_framework import routers
from rest_framework.authtoken import views as authviews

from . import views

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter(trailing_slash=False)
router.register(r'users', views.UserViewSet)
router.register(r'regions', views.RegionViewSet)
router.register(r'schools', views.SchoolViewSet)
router.register(r'grades', views.GradeViewSet)
router.register(r'subjects', views.SubjectViewSet)
router.register(r'tags', views.TagViewSet)
router.register(r'levels', views.LevelViewSet)
router.register(r'profiles', views.ProfileViewSet)
router.register(r'teachers', views.TeacherViewSet)
router.register(r'memberservices', views.MemberserviceViewSet)
router.register(r'coupons', views.CouponViewSet)
router.register(r'weeklytimeslots', views.WeeklyTimeSlotViewSet)
router.register(r'parents', views.ParentViewSet)
router.register(r'timeslots', views.TimeSlotViewSet)
router.register(r'orders', views.OrderViewSet)
router.register(r'comments', views.CommentViewSet)
router.register(r'favorites', views.FavoriteViewSet)
router.register(r'liveclasses', views.LiveClassViewSet)
router.register(r'exercise', views.ExerciseSubmitViewSet)


urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='app/index.html')),
    url(r'^api-auth', include(
        'rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/teachers/(?P<teacher_id>\d+)/weeklytimeslots',
        views.TeacherWeeklyTimeSlot.as_view(),
        name='teacher_weekly_time_slot'),
    url(r'^api/v1/token-auth', authviews.obtain_auth_token),
    url(r'^api/v1/policy', views.Policy.as_view(), name='policy'),
    url(r'^api/v1/subject/(?P<subject_id>\d+)/record',
        views.SubjectRecord.as_view(), name='subject_record'),
    url(r'^api/v1/sms', views.Sms.as_view(), name='sms'),
    url(r'^api/v1/charge_succeeded', views.ChargeSucceeded.as_view(),
        name='charge_succeeded'),
    url(r'^api/v1/concrete/timeslots', views.ConcreteTimeSlots.as_view(),
        name='concrete_time_slot'),
    url(r'^api/v1/unpaid_count', views.UnpaidCount.as_view(),
        name='unpaid_count'),
    url(r'^api/v1/my_center', views.ParentCenter.as_view(),
        name='my_center'),
    url(r'^api/v1/study_report(\/?)$', views.StudyReportView.as_view(),
        name='study_report_api'),
    url(r'^api/v1/study_report/(?P<subject>\w+)(\/?)$', views.StudyReportView.as_view(),
        name="study_report_subject"),
    # url(r'^api/v1/study_report/(?P<subject>\w+)/(?P<category>\w+)(\/?)$', views.StudyReportView.as_view(),
    #     name="study_report_category"),
    url(r'^api/v1/teacher/(?P<teacher_id>\d+)/school/(?P<school_id>\d+)/prices',
        views.TeacherSchoolPrices.as_view(), name='teacher_school_prices'),
    url(r'^api/v1/pad/login', views.PadLogin.as_view(), name='pad_login'),
    url(r'^api/v1/pad/status', views.PadStatus.as_view(), name='pad_status'),
    url(r'^api/v1/pad/question', views.PadQuestion.as_view(), name='pad_question'),
    url(r'^api/v1/pad/submit', views.PadSubmit.as_view(), name='pad_submit'),
    url(r'^api/v1/', include(router.urls)),
]

server/server/urls.py
import django
import os
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.conf import settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('app.urls')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^teacher/', include('teacher.urls', namespace='teacher')),
    url(r'^staff/', include('staff.urls', namespace='staff')),
    url(r'^import_/', include('import_.urls', namespace='import_')),
    url(r'^wechat/', include('wechat.urls', namespace='wechat')),
    url(r'^lecturer/', include('lecturer.urls', namespace='lecturer')),
    url(r'^upload/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^api/v1/(?P<path>.*(\.json|\.yaml))$', django.views.static.serve,
        {'document_root': os.path.join(BASE_DIR, "app", "api")}),
    url(r'^', include('web.urls', namespace='web')),
    url(r'^favicon\.ico$', django.views.generic.base.RedirectView.as_view(
        url=static('common/icons/favicon.ico'), permanent=True)),
]

server/teacher/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url(r'^login$', views.TeacherLogin.as_view(), name="login"),
    url(r'^logout/$', auth_views.logout_then_login, {"login_url": "/web/teacher"}, name="logout"),
    url(r'^doc/agree/$', TemplateView.as_view(template_name="teacher/doc/policy.html"), name="doc-agree"),
    url(r'^information/complete$', views.InformationComplete.as_view(), name="complete-information"),
    url(r'^register/progress$', views.RegisterProgress.as_view(), name="register-progress"),
    url(r'^first_page/$', views.FirstPage.as_view(), name="first-page"),
    url(r'^$', views.FirstPage.as_view(), name="default-page"),
    url(r'^my_school_timetable/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.MySchoolTimetable.as_view(), name="my-school-timetable"),
    url(r'^my_students/(?P<student_type>[0-9]{1})/(?P<page_offset>[0-9]+)/$', views.MyStudents.as_view(), name="my-students"),
    url(r'^my_evaluation/(?P<comment_type>[0-9]+)/(?P<page_offset>[0-9]+)/$', views.MyEvaluation.as_view(), name="my-evaluation"),
    url(r'^my_evaluation/(?P<comment_type>[0-9]+)/(?P<page_offset>[0-9]+)/reply/comment/(?P<id>\d+)$', views.CommentReply.as_view(), name="reply-comment"),
    url(r'^my_wallet/withdrawal/$', views.MyWalletWithdrawal.as_view(), name="my-wallet-withdrawal"),
    url(r'^my_wallet/withdrawal/result/$', views.MyWalletWithdrawalResult.as_view(), name="my-wallet-withdrawal-result"),
    url(r'^my_wallet/withdrawal/record/$', views.MyWalletWithdrawalRecord.as_view(), name="my-wallet-withdrawal-record"),
    url(r'^my_level/$', views.MyLevel.as_view(), name="my-level"),
    url(r'^generate_sms/$', views.GenerateSMS.as_view(), name="generate-sms"),
    url(r'^withdrawal_request/$', views.WithdrawalRequest.as_view(), name="withdrawal_request"),
    url(r'^certificate/$', views.CertificateView.as_view(), name="certificate"),
    url(r'^certificate/id/$', views.CertificateIDView.as_view(), name="certificate-id"),
    url(r'^certificate/academic/$', views.CertificateAcademicView.as_view(), name="certificate-academic"),
    url(r'^certificate/teaching/$', views.CertificateTeachingView.as_view(), name="certificate-teaching"),
    url(r'^certificate/english/$', views.CertificateEnglishView.as_view(), name="certificate-english"),
    url(r'^certificate/others/$', views.CertificateOthersView.as_view(), name="certificate-others"),
    url(r'^highscore/$', views.HighscoreView.as_view(), name="highscore"),
    url(r'^basic_doc/$', views.BasicDocument.as_view(), name="basic_doc"),
    url(r'^achievement$', views.AchievementView.as_view(), name="achievement"),
    url(r'^achievement/(?P<action>\w+)$', views.AchievementView.as_view(), name="achievement-add"),
    url(r'^achievement/(?P<action>\w+)/(?P<id>\d+)$', views.AchievementView.as_view(), name="achievement-edit"),
    url(r'^wallet/$', views.WalletView.as_view(), name="wallet"),
    url(r'^wallet/(?P<action>histories)/$', views.WalletView.as_view(), name="wallet-histories"),
    url(r'^wallet/bankcard/add/$', views.WalletBankcardView.as_view(), name="wallet-bankcard-add"),
    url(r'^wallet/bankcard/add/(?P<step>success)/$', views.WalletBankcardView.as_view(), name="wallet-bankcard-add-success"),
    url(r'^my_students/letter/(?P<student_type>[0-9]{1})/(?P<page_offset>[0-9]+)/(?P<student_id>[0-9]+)/$', views.StudentLetter.as_view(), name="student-letter"),
    url(r'^my_students/letter/(?P<student_type>[0-9]{1})/(?P<page_offset>[0-9]+)/(?P<student_id>[0-9]+)/(?P<letter_id>[0-9]+)$', views.StudentLetterView.as_view(), name="student-letter-view"),
    url(r'^kuailexue/account/$', views.KLXAccountView.as_view(), name="klx-account"),
    url(r'^schedule/weekly_config/$', views.ScheduleWeeklyConfigView.as_view(), name="schedule-weekly-config"),
]

server/teacher/forms.py
from django import forms


class CommentReplyForm(forms.Form):
    reply = forms.CharField(max_length=100, min_length=6,
                            widget=forms.Textarea(attrs={"class": "reply-content"}),
                            label=None
                            )

server/templates/teacher/certificate/certificate_id.html
{% extends "teacher/teacher_frame.html" %}

{% load staticfiles %}
{% load compile_static %}
{% block title %}
    资质认证
{% endblock %}
{% block addition_header %}
    <link rel="stylesheet" href="{% static 'teacher/less/certificate/certificate.less'|compile %}?{% lorem 1 w random%}">
{% endblock %}
{% block addition_js %}
    <script src="{% static 'teacher/js/certificate/certificate.js' %}?{% lorem 1 w random%}"></script>
    <script>
        var certOverviewPageUrl = "{% url 'teacher:certificate' %}";
        var nextPage = "{{ next_url }}";
    </script>
{% endblock %}

{% block breadcrumbs %}
    <span class="title">个人设置</span>
    &gt;
    <a href="{% url 'teacher:certificate' %}"><span>资质认证</span></a>
    &gt;
    <span>身份认证</span>
{% endblock %}

{% block maincontent %}
    <div class="certificate-box">
        <form class="form-horizontal" id="certEditForm" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">姓名</label>
                <div class="col-sm-5">
                    <p class="form-control-static">{{ teacherName }}</p>
                </div>
            </div>
         {% if cert_id_held.is_to_audit or cert_id_held.is_approved %}
            <div class="form-group">
                <label for="id_num" class="col-sm-2 control-label">身份证号</label>
                <div class="col-sm-5">
                    <p class="form-control-static">{{ cert_id_held.mask_id_num }}</p>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">{# empty #}</div>
                <div class="col-sm-2">
                    <div class="img-upload-box" imgName="idHeldImg">
                        <div class="img-box">
                            <img src={{ idHeldUrl }}>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="img-upload-box" imgName="idFrontImg">
                        <div class="img-box">
                            <img src={{idFrontUrl}}>
                        </div>
                    </div>
                </div>
            </div>
         {% else %}
            <div class="form-group">
                <label for="id_num" class="col-sm-2 control-label">身份证号</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="id_num" name="id_num" value="{{ id_num }}" placeholder="身份证号"
                           {% if verified %}readonly="readonly"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">{# empty #}</div>
                <div class="col-sm-3">
                    <div class="img-upload-box" imgName="idHeldImg">
                        <div class="img-text">手持身份证照片</div>
                        <div class="img-box" {% if not idHeldUrl %} style="display: none" {% endif %}>
                            <img src={{ idHeldUrl }}>
                        </div>
                        <div class="img-preview-box"><img src=""></div>
                        <div class="uploading-hint-box"></div>
                        <span class="file-input-mask text-center">
                            <span>上传图片</span>
                            <input title="请选择图片" type="file" name="idHeldImg" multiple="" {% if verified %}disabled="disabled"{% endif %}/>
                        </span>
                    </div>
                </div>
                <div class="col-sm-3">
                    <img src="{% static 'teacher/images/cert/eg_id_held.png' %}"/>
                </div>
                <div class="col-sm-4">
                    <span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="right"
                          title="<div class='text-left'>1.免冠, 保持五官清晰<br>2.手持证件, 请勿遮挡证件信息</div>"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">{# empty #}</div>
                <div class="col-sm-3">
                    <div class="img-upload-box" imgName="idFrontImg">
                        <div class="img-text">身份证正面</div>
                        <div class="img-box" {% if not idFrontUrl %} style="display: none" {% endif %}>
                            <img src={{idFrontUrl}}>
                        </div>
                        <div class="img-preview-box"><img src=""></div>
                        <div class="uploading-hint-box"></div>
                        <span class="file-input-mask text-center">
                            <span>上传图片</span>
                            <input title="请选择图片" type="file" name="idFrontImg" multiple="" {% if verified %}disabled="disabled"{% endif %}/>
                        </span>
                    </div>
                </div>
                <div class="col-sm-3">
                    <img src="{% static 'teacher/images/cert/eg_id_front.png' %}"/>
                </div>
                <div class="col-sm-4">
                    <span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="right"
                          title="<div class='text-left'>1.证件与手持证件一致<br>2.证件文字清晰, 无更改</div>"></span>
                </div>
            </div>
            <div class="form-group {% if error_msg %}has-error{% endif %}">
                <div class="col-sm-2">{# empty #}</div>
                <div class="col-sm-10">
                    <span class="help-block">{{ error_msg }}</span>
                    <button type="button" class="btn btn-success {% if verified %}disabled{% endif %}" {% if verified %}title="已通过认证的不需要修改" {% else %}data-action="save"{% endif %}>保存</button>
                    <button type="button" class="btn btn-default" data-action="cancel">取消</button>
                </div>
            </div>
         {% endif %}
        </form>
    </div>
{% endblock %}

server/templates/teacher/certificate/certificate_others.html
{% extends "teacher/teacher_frame.html" %}

{% load staticfiles %}
{% load compile_static %}
{% block title %}
    资质认证
{% endblock %}
{% block addition_header %}
    <link rel="stylesheet" href="{% static 'teacher/less/certificate/certificate.less'|compile %}?{% lorem 1 w random%}">
{% endblock %}
{% block addition_js %}
    <script src="{% static 'teacher/js/certificate/certificate.js' %}?{% lorem 1 w random%}"></script>
    <script>
        var certOverviewPageUrl = "{% url 'teacher:certificate' %}";
        var nextPage = "";
    </script>
{% endblock %}

{% block breadcrumbs %}
    <span class="title">个人设置</span>
    &gt;
    <a href="{% url 'teacher:certificate' %}"><span>资质认证</span></a>
    &gt;
    <span>其他资质认证</span>
{% endblock %}

{% block maincontent %}
    <div class="list-group" id="otherCertsList">
        {% for cert in otherCerts %}
            <div class="row list-group-item" certId="{{ cert.id }}">
                <div class="col-md-3">
                    <div class="cert-name">{{ cert.name }}</div>
                    <div class="cert-img-view"><img src="{{ cert.img_url }}"></div>
                </div>
                <div class="col-md-7"></div>
                <div class="col-md-2 col-btns">
                    <a class="btn btn-default" href="javascript:void(0)" data-action="edit-cert">编辑</a>
                    <a class="btn btn-default" href="javascript:void(0)" data-action="delete-cert">删除</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="certificate-box">
        <form class="form-horizontal" id="certEditForm" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" id="id" name="id">
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">证书名称</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="name" name="name" value="" placeholder="">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">{# empty #}</div>
                <div class="col-sm-3">
                    <div class="img-upload-box">
                        <div class="img-box">
                            <img src="">
                        </div>
                        <div class="img-preview-box"><img src=""></div>
                        <div class="uploading-hint-box"></div>
                        <span class="file-input-mask text-center">
                            <span>上传图片</span>
                            <input title="请选择图片" type="file" name="certImg" multiple=""/>
                        </span>
                    </div>
                </div>
                <div class="col-sm-4">
                    <span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="right"
                          title="<div class='text-left'>请上传您的证书照片</div>"></span>
                </div>
            </div>
            <div class="form-group {% if error_msg %}has-error{% endif %}">
                <div class="col-sm-2">{# empty #}</div>
                <div class="col-sm-10">
                    <span class="help-block">{{ error_msg }}</span>
                    <button type="button" class="btn btn-success" data-action="save">保存</button>
                    <button type="button" class="btn btn-default" data-action="cancel">取消</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

server/templates/teacher/certificate/certificate_simple.html
{% extends "teacher/teacher_frame.html" %}

{% load staticfiles %}
{% load compile_static %}
{% block title %}
    资质认证
{% endblock %}
{% block addition_header %}
    <link rel="stylesheet" href="{% static 'teacher/less/certificate/certificate.less'|compile %}?{% lorem 1 w random%}">
{% endblock %}
{% block addition_js %}
    <script src="{% static 'teacher/js/certificate/certificate.js' %}?{% lorem 1 w random%}"></script>
    <script>
        var certOverviewPageUrl = "{% url 'teacher:certificate' %}";
        var nextPage = "{{ next_url }}";
    </script>
{% endblock %}


{% block breadcrumbs %}
    <span class="title">个人设置</span>
    &gt;
    <a href="{% url 'teacher:certificate' %}"><span>资质认证</span></a>
    &gt;
    <span>{{ cert_title }}</span>
{% endblock %}

{% block maincontent %}
    <div class="certificate-box">
        <form class="form-horizontal" id="certEditForm" method="post" enctype="multipart/form-data">
            {% csrf_token %}
         {% if cert.is_to_audit or cert.is_approved %}
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">{{ cert_name }}</label>
                <div class="col-sm-5">
                    <p class="form-control-static">{{ name_val }}</p>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">{# empty #}</div>
                <div class="col-sm-3">
                    <div class="img-upload-box">
                        <div class="img-box">
                            <img src={{ cert_img_url }}>
                        </div>
                    </div>
                </div>
            </div>
         {% else %}
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">{{ cert_name }}</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="name" name="name" value="{{ name_val }}" placeholder="{{ name_val_hint }}">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">{# empty #}</div>
                <div class="col-sm-3">
                    <div class="img-upload-box">
                        <div class="img-box">
                            <img src={{ cert_img_url }}>
                        </div>
                        <div class="img-preview-box"><img src=""></div>
                        <div class="uploading-hint-box"></div>
                        <span class="file-input-mask text-center">
                            <span>上传图片</span>
                            <input title="请选择图片" type="file" name="certImg" multiple=""/>
                        </span>
                    </div>
                </div>
                <div class="col-sm-4">
                    <span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="right"
                          title="<div class='text-left'>{{ hint_content }}</div>"></span>
                </div>
            </div>
            <div class="form-group {% if error_msg %}has-error{% endif %}">
                <div class="col-sm-2">{# empty #}</div>
                <div class="col-sm-10">
                    <span class="help-block">{{ error_msg }}</span>
                    <button type="button" class="btn btn-success" data-action="save">保存</button>
                    <button type="button" class="btn btn-default" data-action="cancel">取消</button>
                </div>
            </div>
         {% endif %}
        </form>
    </div>
{% endblock %}

server/templates/teacher/certificate/overview.html
{% extends "teacher/teacher_frame.html" %}

{% load staticfiles %}
{% load compile_static %}
{% block title %}
    资质认证
{% endblock %}
{% block addition_header %}
    <link rel="stylesheet" href="{% static 'teacher/less/certificate/certificate.less'|compile %}?{% lorem 1 w random%}">
{% endblock %}

{% block breadcrumbs %}
    <span class="title">个人设置</span>
    &gt;
    <span>资质认证</span>
{% endblock %}

{% block maincontent %}
    {% csrf_token %}
    <div class="list-group" id="certificationsList">
        <div class="row list-group-item">
            <div class="col-flag">
                {% if cert_id and cert_id.verified %}
                    <span><img src="{% static 'common/icons/verified.png' %}"></span>
                {% else %}
                    <span class="not-verified">未认证</span>
                {% endif %}
            </div>
            <div class="col-md-2">身份认证</div>
            <div class="col-md-5 note">成为麻辣老师必须通过真实身份认证同时保障您的合法权益</div>
            <div class="pull-right">
                {% if cert_id and cert_id.is_approved %}
                    {% if cert_id.show_hint_once %}
                        <span class="hint yes">审核通过!</span>
                    {% endif %}
                    <a class="btn btn-default" href="{% url 'teacher:certificate-id' %}">查看</a>
                {% elif cert_id and cert_id.is_rejected %}
                    {% if cert_id.show_hint_once %}
                        <span class="hint no">未通过审核!</span>
                    {% endif %}
                    <a class="btn btn-success" href="{% url 'teacher:certificate-id' %}">重新认证</a>
                {% elif cert_id and cert_id.is_to_audit %}
                    <span class="fake-btn">认证中</span>
                {% else %}
                    <a class="btn btn-success" href="{% url 'teacher:certificate-id' %}">认证</a>
                {% endif %}
            </div>
        </div>
        <div class="row list-group-item">
            <div class="col-flag">
                {% if cert_academic and cert_academic.verified %}
                    <span><img src="{% static 'common/icons/verified.png' %}"></span>
                {% else %}
                    <span class="not-verified">未认证</span>
                {% endif %}
            </div>
            <div class="col-md-2">学历认证</div>
            <div class="col-md-5 note">进行学历认证可以提升学生对您的信任度</div>
            <div class="pull-right">
                {% if cert_academic and cert_academic.is_approved %}
                    {% if cert_academic.show_hint_once %}
                        <span class="hint yes">审核通过!</span>
                    {% endif %}
                    <a class="btn btn-default" href="{% url 'teacher:certificate-academic' %}">查看</a>
                {% elif cert_academic and cert_academic.is_rejected %}
                    {% if cert_academic.show_hint_once %}
                        <span class="hint no">未通过审核!</span>
                    {% endif %}
                    <a class="btn btn-success" href="{% url 'teacher:certificate-academic' %}">重新认证</a>
                {% elif cert_academic and cert_academic.is_to_audit %}
                    <span class="fake-btn">认证中</span>
                {% else %}
                    <a class="btn btn-success" href="{% url 'teacher:certificate-academic' %}">认证</a>
                {% endif %}
            </div>
        </div>
        <div class="row list-group-item">
            <div class="col-flag">
                {% if cert_teaching and cert_teaching.verified %}
                    <span><img src="{% static 'common/icons/verified.png' %}"></span>
                {% else %}
                    <span class="not-verified">未认证</span>
                {% endif %}
            </div>
            <div class="col-md-2">教师资格认证</div>
            <div class="col-md-5 note">证明您的教师身份资格获得更多学生的关注</div>
            <div class="pull-right">
                {% if cert_teaching and cert_teaching.is_approved %}
                    {% if cert_teaching.show_hint_once %}
                        <span class="hint yes">审核通过!</span>
                    {% endif %}
                    <a class="btn btn-default" href="{% url 'teacher:certificate-teaching' %}">查看</a>
                {% elif cert_teaching and cert_teaching.is_rejected %}
                    {% if cert_teaching.show_hint_once %}
                        <span class="hint no">未通过审核!</span>
                    {% endif %}
                    <a class="btn btn-success" href="{% url 'teacher:certificate-teaching' %}">重新认证</a>
                {% elif cert_teaching and cert_teaching.is_to_audit %}
                    <span class="fake-btn">认证中</span>
                {% else %}
                    <a class="btn btn-success" href="{% url 'teacher:certificate-teaching' %}">认证</a>
                {% endif %}
            </div>
        </div>
        <div class="row list-group-item">
            <div class="col-flag">
                {% if cert_other and cert_other.verified %}
                    <span><img src="{% static 'common/icons/verified.png' %}"></span>
                {% else %}
                    <span class="not-verified">未认证</span>
                {% endif %}
            </div>
            <div class="col-md-2">其他认证</div>
            <div class="col-md-5 note">其他认证信息可以提升学生对您的认可度</div>
            <div class="pull-right">
                {% if cert_other and cert_other.is_approved %}
                    <a class="btn btn-default" href="{% url 'teacher:certificate-others' %}">查看</a>
                {% else %}
                    <a class="btn btn-success" href="{% url 'teacher:certificate-others' %}">认证</a>
                {% endif %}
            </div>
        </div>
{# 只有英语老师才有 "英语水平认证" #}
      {% if isEnglishTeacher %}
        <div class="row list-group-item">
            <div class="col-flag">
                {% if cert_english and cert_english.verified %}
                    <span><img src="{% static 'common/icons/verified.png' %}"></span>
                {% else %}
                    <span class="not-verified">未认证</span>
                {% endif %}
            </div>
            <div class="col-md-2">英语水平认证</div>
            <div class="col-md-5 note">英语水平认证可以展现您的英语实力获得更多认可度</div>
            <div class="pull-right">
                {% if cert_english and cert_english.is_approved %}
                    {% if cert_english.show_hint_once %}
                        <span class="hint yes">审核通过!</span>
                    {% endif %}
                    <a class="btn btn-default" href="{% url 'teacher:certificate-english' %}">查看</a>
                {% elif cert_english and cert_english.is_rejected %}
                    {% if cert_english.show_hint_once %}
                        <span class="hint no">未通过审核!</span>
                    {% endif %}
                    <a class="btn btn-success" href="{% url 'teacher:certificate-english' %}">重新认证</a>
                {% elif cert_english and cert_english.is_to_audit %}
                    <span class="fake-btn">认证中</span>
                {% else %}
                    <a class="btn btn-success" href="{% url 'teacher:certificate-english' %}">认证</a>
                {% endif %}
            </div>
        </div>
      {% endif %}
    </div>
{% endblock %}